[client]
showSidebarNavigation = false

[server]
headless = true

[theme]
primaryColor = "#142036"
backgroundColor = "#EEF1F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#142036"
font = "sans serif"
